In [1]:
from tensorflow.keras.preprocessing import image

In [5]:
img = image.load_img('./images/1163.jpg', target_size=(224,224))

In [6]:
img_array = image.img_to_array(img)
img_array

array([[[255., 255., 255.],
        [255., 255., 255.],
        [255., 255., 255.],
        ...,
        [255., 255., 255.],
        [255., 255., 255.],
        [255., 255., 255.]],

       [[255., 255., 255.],
        [255., 255., 255.],
        [255., 255., 255.],
        ...,
        [255., 255., 255.],
        [255., 255., 255.],
        [255., 255., 255.]],

       [[255., 255., 255.],
        [255., 255., 255.],
        [255., 255., 255.],
        ...,
        [255., 255., 255.],
        [255., 255., 255.],
        [255., 255., 255.]],

       ...,

       [[255., 255., 255.],
        [255., 255., 255.],
        [255., 255., 255.],
        ...,
        [255., 255., 255.],
        [255., 255., 255.],
        [255., 255., 255.]],

       [[255., 255., 255.],
        [255., 255., 255.],
        [255., 255., 255.],
        ...,
        [255., 255., 255.],
        [255., 255., 255.],
        [255., 255., 255.]],

       [[255., 255., 255.],
        [255., 255., 255.],
        [255., 2

In [8]:
img_array.shape

(224, 224, 3)

In [9]:
import numpy as np
expanded_img_array = np.expand_dims(img_array, axis=0)
print(expanded_img_array.shape)

(1, 224, 224, 3)


In [12]:
import tensorflow
from tensorflow.keras.layers import GlobalMaxPooling2D
from tensorflow.keras.applications.resnet50 import ResNet50,preprocess_input

In [13]:
model = ResNet50(weights='imagenet', include_top=False, input_shape=(224, 224, 3))
model.trainable = False

model = tensorflow.keras.Sequential([
    model,
    GlobalMaxPooling2D()
])

In [14]:
preprocessed_img = preprocess_input(expanded_img_array)

In [15]:
print(preprocessed_img.shape)

(1, 224, 224, 3)


In [16]:
model.predict(preprocessed_img)

1/1 [==============================] - 0s 407ms/step


array([[ 1.6351368, 19.324406 ,  1.8080325, ...,  1.1685799, 17.437439 ,
        12.099041 ]], dtype=float32)

In [19]:
from numpy.linalg import norm
model.predict(preprocessed_img).flatten()/norm(model.predict(preprocessed_img).flatten())

1/1 [==============================] - 0s 41ms/step


array([0.00491866, 0.05812983, 0.00543875, ..., 0.00351521, 0.05245364,
       0.03639518], dtype=float32)